### ISSUE TITLE
How to get this working on-premise?

### ISSUE THREAD

**Issue by peder** [mmanela/vsts-workitem-recentlyviewed#2]
I don't see a way to activate this on TFS 2015 Update 2

**Comment by mmanela** [comment]
This is only for the new work item form which is not available in TFS 2015. I will update the readme with this information. Sorry for the confusion.

**Comment by peder** [comment]
Would this work with the new work item form in TFS '15'?

**Comment by mmanela** [comment]
Yes it does.
