### ISSUE TITLE
Who recently viewed a work item? by Matthew Manela is taking longer than expected to load.Learn More about this extension, including available support options.

### ISSUE THREAD

**Issue by SimonLuckenuik** [mmanela/vsts-workitem-recentlyviewed#3]
Hi,
Beginning of this week, the plug-in started to timeout when trying to load. Looking at the Debug Console, I can see that some errors are now being written:

```
TypeError: Cannot read property 'tagName' of undefined
    at RecentlyViewedList.n._getEnhancementOption (Controls.js:2)
    at RecentlyViewedList.t._createElement (Controls.js:2)
    at RecentlyViewedList.t._createIn (Controls.js:2)
    at RecentlyViewedList.t.createIn (Controls.js:2)
    at Function.t.createIn (Controls.js:2)
    at RecentlyViewedGroupView.initialize (RecentlyViewed.js:27)
    at recentlyViewedGroup.html:24
    at vss-bundle-ext-core-vLzRDA5ggzZEJHv-FnnlZ3C81KCQnL7UJ2rU5ikDvpj8=:305
    at Object.execCb (Content?bundle=vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:263)
    at pt.check (Content?bundle=vss-bundle-basejs-vSljho_k690hofnoiyEmz5e4nME3rw4wV1Y8HgrqvV9Q=:263)
```
Plug-in placeholder looks like this:
![image](https://user-images.githubusercontent.com/13141534/52067048-c173ac80-2547-11e9-94a3-1162d432ea0e.png)

Thanks for this great plug-in that we use daily! :)
Simon

**Comment by mmanela** [comment]
Odd it will works for me on my account. Can you give me some more details

1. Is this always happening? Even after a full page refresh?
2. Which browser are you using?
3. Which is your AzureDevOps org name (dev.azure.com/NAME or NAME.visualstudio.com)

**Comment by qtzar** [comment]
Having the same issue, within the past few days the plugin is failing with the same errors.
Using Chrome/Mac ( but also tested with Firefox/Mac and IE Edge/Win )
Using the NAME.visualstudio.com format for access to site.

**Comment by mmanela** [comment]
@qtzar  Can you share what the NAME is? And does it consist after a full-page refresh?

**Comment by SimonLuckenuik** [comment]
1) It is happening at initial loading, and after a refresh as well (we are not able to see the history anymore).
2) Chrome Version 71.0.3578.98 (Official Build) (64-bit) on Windows 10
3) It happens both on https://dev.azure.com/tenant and https://tenant.visualstudio.com. We have the following preview features enabled in the account: 
![image](https://user-images.githubusercontent.com/13141534/52278853-0e7bc800-2926-11e9-91b8-90d88dd2cdca.png)

**Comment by mmanela** [comment]
I just got a repro of this, I am investigating...

**Comment by mmanela** [comment]
@trevorsg is working on a fix to the service.

**Comment by CampbellNash** [comment]
Yeah I can confirm we are having the same issues...

**Comment by qtzar** [comment]
It looks like this extension is working again in Azure DevOps.
I suspect a change on their end with the latest release.

**Comment by mayeager22** [comment]
I just installed the extension today and it doesn't load at all...no time out, just keeps spinning.

**Comment by mmanela** [comment]
@mayeager22  What is your org name (dev.azure.com/ORG or ORG.visualstudio.com)

**Comment by mayeager22** [comment]
It is myeager-phidiax.

**Comment by mmanela** [comment]
And do you see errors in the console log?

**Comment by mayeager22** [comment]
I am not sure what you mean by “console log”.

**Comment by mmanela** [comment]
In the browser open up the developer console by pressing F12. There is a console tab where it lists errors. Please repro your issue and report what errors are logged there

**Comment by mayeager22** [comment]
It just stays at “Loading” (as shown below)…console log included below as well.

[cid:image001.png@01D4DFE6.9696E2D0]
[cid:image002.png@01D4DFE7.070F4E30]

**Comment by mmanela** [comment]
@mayeager22  Your images do not render

**Comment by mayeager22** [comment]
@mmanela Updated image in post above.

**Comment by mmanela** [comment]
Thanks I can repro the issue

**Comment by mmanela** [comment]
@mayeager22  I pushed an update to fix this, let me know

**Comment by mayeager22** [comment]
I can confirm that it loads in an acceptable amount of time now.

Thank you!
